name: Deploy to production

on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Configure SSH
              run: |
                  mkdir ~/.ssh/
                  echo "$SSH_KEY" > ~/.ssh/deploy.key
                  chmod 600 ~/.ssh/deploy.key
                  cat >>~/.ssh/config <<END
                  Host ector
                    HostName ector.websanity.com
                    User root
                    IdentityFile ~/.ssh/deploy.key
                    StrictHostKeyChecking no
                  END
              env:
                  SSH_KEY: ${{ secrets.DEPLOY_KEY }}

            - name: Send files
              run: "rsync ${{ env.FLAGS }} ${{ env.EXCLUDE }} ${{ env.LOCAL }} ector:${{ env.REMOTE }}"
              env:
                  FLAGS: --archive --verbose --compress --protect-args --delete --cvs-exclude
                  EXCLUDE: --exclude .github --exclude README.md --exclude .gitignore --exclude /css/*.scss --exclude /images/headshotraw.jpg --exclude github.svg --exclude github-mark.svg --exclude at-symbol-cutout.svg --exclude linkedin-cutout.svg
                  LOCAL: ./
                  REMOTE: /var/www/patrickdwyer.com/
